[project]
name = "dagster-test-reload-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dagster>=1.10.20",
    "dagster-webserver>=1.10.20",
]
